version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: /home/docs/checkouts/readthedocs.org/user_builds/oc-lettings-fr/checkouts/latest/docs/source/conf.py 

formats: all