# CircleCI configuration file
version: 2.1

jobs:
  # Job one with a unique name
  build:
    docker:
      - image: cimg/python:3.11.5

    steps:
      - checkout
      - run: python --version

  test:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: Test preparation
          command: |
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            mkdir test-results
            pytest --junitxml=test-results/junit.xml
      - store_artifacts:
          path: test-results
  
  coverage:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: coverage preparation
          command: |
            pip install -r requirements.txt
      - run:
          name: run coverage
          command: |
            coverage run -m pytest
            coverage report
            coverage html
      - store_artifacts:
          path: htmlcov

  linting:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: linting preparation
          command: |
            pip install -r requirements.txt
      - run:
          name: Linting
          command: |
            flake8



  # # Job two with a unique name
  # test:
  #   docker:
  #     - image: cimg/python:3.11.5
  #   steps:
  #     - checkout

workflows:
# Name of workflow
  build_and_test:
    # List of jobs that will run
    jobs:
      - build
      - test
      - coverage
      - linting