# CircleCI configuration file
version: 2.1

jobs:
  # Job one with a unique name
  build:
    docker:
      - image: python:3.11.5-alpine3.18
    steps:
      - checkout
      - run: pip install -r requirements.txt
  # Job two with a unique name
  test:
    docker:
      - image: python:3.11.5-alpine3.18
    steps:
      - checkout
      - run: pytest

workflows:
  # Name of workflow
  build_and_test:
    # List of jobs that will run
    jobs:
      - build
      - test