# CircleCI configuration file
version: 2.1

jobs:
  # Job one with a unique name
  build:
    docker:
      - image: cimg/python:3.11.5

    steps:
      - checkout
      - run: python --version

  test:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: Test preparation
          command: |
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            mkdir test-results
            pytest --junitxml=test-results/junit.xml
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: terst-results
  
  coverage:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: coverage preparation
          command: |
            pip install -r requirements.txt
      - run:
          name: run coverage
          command: |
            coverage run -m pytest
            coverage report
            coverage html
      - store_artifacts:
          path: htmlcov

  linting:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: linting
          command: |
            pip install -r requirements.txt
            flake8

  deploy:
    docker:
      - image: cimg/python:3.11.5
      environment:
        SENTRY_DSN: $SENTRY_DSN
        SECRET_KEY: $SECRET_KEY
    steps:
      - checkout
      - run:
          name: Deploy main to heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master



workflows:
# Name of workflow
  build_and_tests:
    # List of jobs that will run
    jobs:
      - build
      - test
      - coverage
      - linting
      - deploy:
          requires:
            - build
            - test
            - coverage
          filters:
            branches:
              only: master
