# CircleCI configuration file
version: 2.1

jobs:
  # Job one with a unique name
  build:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run: python --version

  test:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: Test preparation
          command: |
            pip install -r requirements.txt
            mkdir test-results
      - run:
          name: Test start
          command: pytest --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
  


  # # Job two with a unique name
  # test:
  #   docker:
  #     - image: cimg/python:3.11.5
  #   steps:
  #     - checkout

workflows:
# Name of workflow
  build_and_test:
    # List of jobs that will run
    jobs:
      - build
      - test