# CircleCI configuration file
version: 2.1

jobs:
  # Job one with a unique name
  build:
    docker:
      - image: cimg/python:3.11.5

    working_directory: /tmp
    steps:
      - checkout
      - run: python --version

  test:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: Test preparation
          command: |
            pip install -r requirements.txt
            mkdir test-results
      - run:
          name: Test start
          command: pytest --junitxml=test-results/junit.xml
      - store_artifacts:
          path: /tmp/test-reports
          destination: python_app
      - store_test_results:
          path: /tmp/test-results
  
  coverage:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: Coverage
          command: |
            pip install -r requirements.txt
            coverage run -m pytest
            coverage report
            coverage html
      - store_artifacts:
          path: /tmp/htmlcov
          destination: html-coverage

  linting:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: Linting
          command: |
            pip install -r requirements.txt
            flake8
      - store_artifacts:
          path: linting



  # # Job two with a unique name
  # test:
  #   docker:
  #     - image: cimg/python:3.11.5
  #   steps:
  #     - checkout

workflows:
# Name of workflow
  build_and_test:
    # List of jobs that will run
    jobs:
      - build
      - test
      - coverage
      - linting