# CircleCI configuration file
version: 2.1

jobs:
  # Job one with a unique name
  build:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run: python --version
      # - run: 
      #     name: Build Docker image
      #     command: docker build --tag oc-lettings



  # # Job two with a unique name
  # test:
  #   docker:
  #     - image: cimg/python:3.11.5
  #   steps:
  #     - checkout

workflows:
# Name of workflow
  build_and_test:
    # List of jobs that will run
    jobs:
      - build